# yapf: disable
# pylint: skip-file
# isort:skip_file
"""Initial revision

Revision ID: 3f5fbc5e54d6
Revises: 
Create Date: 2017-12-05 21:27:08.462193

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import FetchedValue
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3f5fbc5e54d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('example_products',
    sa.Column('id', sa.Integer(), server_default=FetchedValue(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('list_price', sa.Numeric(), nullable=True),
    sa.Column('sell_price', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('example_users',
    sa.Column('id', sa.Integer(), server_default=FetchedValue(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=FetchedValue(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('example_orders',
    sa.Column('id', sa.Integer(), server_default=FetchedValue(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('shipping_address', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('item_subtotal', sa.Numeric(), nullable=True),
    sa.Column('tax', sa.Numeric(), nullable=True),
    sa.Column('total', sa.Numeric(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=FetchedValue(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['example_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_example_orders_first_name'), 'example_orders', ['first_name'], unique=False)
    op.create_index(op.f('ix_example_orders_last_name'), 'example_orders', ['last_name'], unique=False)
    op.create_table('example_variants',
    sa.Column('id', sa.Integer(), server_default=FetchedValue(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['example_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('example_inventorys',
    sa.Column('id', sa.Integer(), server_default=FetchedValue(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('available_to_sell', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['example_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('example_supplier_fragments',
    sa.Column('id', sa.Integer(), server_default=FetchedValue(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['example_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('example_line_items',
    sa.Column('id', sa.Integer(), server_default=FetchedValue(), nullable=False),
    sa.Column('supplier_fragment_id', sa.Integer(), nullable=True),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(), nullable=True),
    sa.Column('tax', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_fragment_id'], ['example_supplier_fragments.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['example_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('example_line_items')
    op.drop_table('example_supplier_fragments')
    op.drop_table('example_inventorys')
    op.drop_table('example_variants')
    op.drop_index(op.f('ix_example_orders_last_name'), table_name='example_orders')
    op.drop_index(op.f('ix_example_orders_first_name'), table_name='example_orders')
    op.drop_table('example_orders')
    op.drop_table('example_users')
    op.drop_table('example_products')
    # ### end Alembic commands ###
